(function(){function buildSidebar(){var sidebar=document.querySelector('.page-sidebar');if(!sidebar)return;var nav=document.querySelector('#navigationBlock');if(!nav)return;var trades=document.querySelector('#tradingHistoryMenu');var settings=document.querySelector('#accountSettingsMenu');var platforms=document.querySelector('#tradingPlatformsMenu');
if(settings){var subItems=settings.querySelectorAll('ul li a');subItems.forEach(function(link){if(link.textContent.trim().toLowerCase().includes('trading account')){link.closest('li').remove();}});}
var selectAccount=document.querySelector('#selectAccount');if(selectAccount)selectAccount.remove();var newNav=document.createElement('div');
var topGroup=document.createElement('ul');topGroup.className='x-navigation';topGroup.style.cssText='list-style:none;padding:0;margin:0;';topGroup.insertAdjacentHTML('beforeend','<li><a href="/"><span class="xn-text">My Account</span></a></li>');topGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/deposit"><span class="xn-text">Fund Account</span></a></li>');topGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/transactions"><span class="xn-text">Transactions</span></a></li>');if(trades){var tradeText=trades.querySelector('.xn-text');if(tradeText)tradeText.textContent='Trades';topGroup.appendChild(trades);}
newNav.appendChild(topGroup);newNav.insertAdjacentHTML('beforeend','<div class="bcm-divider"></div>');
newNav.insertAdjacentHTML('beforeend','<div class="bcm-group-label"><span class="fa fa-files-o"></span>ACCOUNT SETTINGS<span class="fa fa-chevron-down bcm-chevron"></span></div>');var settingsGroup=document.createElement('ul');settingsGroup.className='x-navigation';settingsGroup.style.cssText='list-style:none;padding:0;margin:0;';settingsGroup.insertAdjacentHTML('beforeend','<li><a href="/accounts"><span class="xn-text">Trading Accounts</span></a></li>');if(settings){var settingsSubItems=settings.querySelectorAll(':scope > ul > li');settingsSubItems.forEach(function(li){settingsGroup.appendChild(li);});}
newNav.appendChild(settingsGroup);newNav.insertAdjacentHTML('beforeend','<div class="bcm-divider"></div>');
newNav.insertAdjacentHTML('beforeend','<div class="bcm-group-label"><span class="fa fa-exchange"></span>REQUESTS<span class="fa fa-chevron-down bcm-chevron"></span></div>');var requestsGroup=document.createElement('ul');requestsGroup.className='x-navigation';requestsGroup.style.cssText='list-style:none;padding:0;margin:0;';requestsGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/request-status"><span class="xn-text">Request Status</span></a></li>');requestsGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/withdraw"><span class="xn-text">Withdrawal</span></a></li>');requestsGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/internal-transfers"><span class="xn-text">Internal Transfer</span></a></li>');requestsGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/change-leverage"><span class="xn-text">Change Leverage</span></a></li>');
newNav.appendChild(requestsGroup);newNav.insertAdjacentHTML('beforeend','<div class="bcm-divider"></div>');
newNav.insertAdjacentHTML('beforeend','<div class="bcm-group-label"><span class="fa fa-download"></span>TRADING PLATFORMS<span class="fa fa-chevron-down bcm-chevron"></span></div>');var platformsGroup=document.createElement('ul');platformsGroup.className='x-navigation';platformsGroup.style.cssText='list-style:none;padding:0;margin:0;';if(platforms){var platformSubItems=platforms.querySelectorAll(':scope > ul > li');platformSubItems.forEach(function(li){platformsGroup.appendChild(li);});}
platformsGroup.insertAdjacentHTML('beforeend','<li><a href="https://webtrader.blackcrownmarkets.com"><span class="xn-text">WebTrader</span></a></li>');newNav.appendChild(platformsGroup);
nav.parentNode.replaceChild(newNav,nav);var welcomeLi=document.querySelector('.desktop-welcome-li');var nameStrong=welcomeLi?welcomeLi.querySelector('.profile-data-name strong'):null;var nameText=nameStrong?nameStrong.textContent.trim():'';var nameMaxChars=18;if(nameText.length>nameMaxChars){nameText=nameText.slice(0,nameMaxChars).trim()+'…';}
if(welcomeLi)welcomeLi.remove();var profileFooter=document.createElement('div');profileFooter.className='bcm-sidebar-footer';profileFooter.innerHTML='<div class="bcm-sidebar-profile"><span class="bcm-sidebar-profile-icon"></span><span class="bcm-sidebar-profile-name">'+nameText+'</span><span class="bcm-sidebar-profile-chevron"></span></div><div class="bcm-divider"></div>';var logoutLink=document.querySelector('.desktop-logout-li a.mb-control[data-box="#mb-signout"]');if(logoutLink){var logoutLi=logoutLink.closest('.desktop-logout-li');logoutLink.classList.add('bcm-sidebar-logout');profileFooter.appendChild(logoutLink);if(logoutLi)logoutLi.style.display='none';}
sidebar.appendChild(profileFooter);
buildDashboardHeader();}
function buildDashboardHeader(){var mainContent=document.querySelector('.page-content-wrap');if(!mainContent)return;var selectEl=document.querySelector('#selectAccounts');var refreshEl=document.querySelector('.refreshWidgets')||document.querySelector('#refreshButton .fa-refresh');var refreshBtn=document.querySelector('#refreshButton');var header=document.createElement('div');header.className='bcm-dash-header';var selectorRow=document.createElement('div');selectorRow.className='bcm-selector-row';if(selectEl){var clonedSelect=selectEl.cloneNode(true);clonedSelect.removeAttribute('id');var selectWrap=document.createElement('div');selectWrap.className='bcm-select-wrap';selectWrap.appendChild(clonedSelect);selectorRow.appendChild(selectWrap);selectEl.closest('form')?selectEl.closest('form').style.display='none':selectEl.parentNode.style.display='none';}
if(refreshBtn){var refreshClone=refreshBtn.cloneNode(true);selectorRow.appendChild(refreshClone);refreshBtn.style.display='none';}
header.appendChild(selectorRow);mainContent.insertBefore(header,mainContent.firstChild);}
function relocateDisclaimers(){var mainContent=document.querySelector('.page-content-wrap');if(!mainContent)return;var disclaimer=document.querySelector('.disclaimer-color');var footer=document.querySelector('.footer-color');if(disclaimer)mainContent.appendChild(disclaimer);if(footer)mainContent.appendChild(footer);}
function buildLoginPage(){var body=document.querySelector('.login-body');if(!body||body.dataset.bcmLogin)return;body.dataset.bcmLogin='1';document.documentElement.classList.add('bcm-login-page');var left=document.createElement('div');left.className='bcm-login-left';while(body.firstChild){left.appendChild(body.firstChild);}var titleEl=left.querySelector('.login-title');if(titleEl){var subtitle=document.createElement('div');subtitle.className='bcm-login-subtitle';subtitle.textContent='Access your Black Crown Markets account to manage your trading with ease.';titleEl.insertAdjacentElement('afterend',subtitle);}var right=document.createElement('div');right.className='bcm-login-right';right.innerHTML='<img class="bcm-login-logo" src="https://ffxlryusmstnfjedleds.supabase.co/storage/v1/object/public/Assets/blackcrown%20white.svg" alt="Black Crown Markets"/>';body.appendChild(left);body.appendChild(right);body.classList.add('bcm-login-card');document.body.appendChild(body);}
function buildRegistrationPage(){var body=document.querySelector('.registration-body');if(!body||body.dataset.bcmLogin)return;body.dataset.bcmLogin='1';document.documentElement.classList.add('bcm-login-page');var left=document.createElement('div');left.className='bcm-login-left';while(body.firstChild){left.appendChild(body.firstChild);}var stepNumbers=left.querySelectorAll('.steps_2 .stepNumber');stepNumbers.forEach(function(el,i){el.textContent=String(i+1);});var right=document.createElement('div');right.className='bcm-login-right';right.innerHTML='<img class="bcm-login-logo" src="https://ffxlryusmstnfjedleds.supabase.co/storage/v1/object/public/Assets/blackcrown%20white.svg" alt="Black Crown Markets"/>';body.appendChild(left);body.appendChild(right);body.classList.add('bcm-login-card');document.body.appendChild(body);}
function adjustSidebarHeight(){var sidebar=document.querySelector('.page-sidebar');var header=document.querySelector('.main-header')||document.querySelector('.x-navigation-horizontal');if(!sidebar||!header)return;var headerHeight=header.getBoundingClientRect().height;sidebar.style.setProperty('min-height','calc(100vh - '+headerHeight+'px)','important');}
function markActiveNavItem(){var links=document.querySelectorAll('.page-sidebar .x-navigation a[href]');var currentPath=window.location.pathname.replace(/\/$/,'')||'/';links.forEach(function(a){var linkPath;try{linkPath=new URL(a.getAttribute('href'),window.location.href).pathname.replace(/\/$/,'')||'/';}catch(e){return;}if(linkPath===currentPath){var li=a.closest('li');if(li)li.classList.add('active');}});}
function initGroupToggles(){var labels=document.querySelectorAll('.page-sidebar .bcm-group-label');labels.forEach(function(label){label.addEventListener('click',function(){label.classList.toggle('bcm-collapsed');var list=label.nextElementSibling;if(list)list.style.display=label.classList.contains('bcm-collapsed')?'none':'';});});}
function buildSidebarToggle(){if(document.querySelector('#bcmSidebarToggle'))return;var sidebar=document.querySelector('.page-sidebar');if(!sidebar)return;var btn=document.createElement('button');btn.id='bcmSidebarToggle';btn.type='button';btn.setAttribute('aria-label','Toggle sidebar');btn.innerHTML='<span class="fa fa-bars"></span>';btn.addEventListener('click',function(){document.documentElement.classList.toggle('bcm-sidebar-collapsed');try{localStorage.setItem('bcmSidebarCollapsed',document.documentElement.classList.contains('bcm-sidebar-collapsed')?'1':'0');}catch(e){}});document.body.appendChild(btn);try{if(localStorage.getItem('bcmSidebarCollapsed')==='1'){document.documentElement.classList.add('bcm-sidebar-collapsed');}}catch(e){}}
function init(){buildSidebar();relocateDisclaimers();buildLoginPage();buildRegistrationPage();adjustSidebarHeight();window.addEventListener('resize',adjustSidebarHeight);markActiveNavItem();initGroupToggles();buildSidebarToggle();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}})();
