(function(){function buildSidebar(){var sidebar=document.querySelector('.page-sidebar');if(!sidebar)return;var nav=document.querySelector('#navigationBlock');if(!nav)return;var trades=document.querySelector('#tradingHistoryMenu');var settings=document.querySelector('#accountSettingsMenu');var platforms=document.querySelector('#tradingPlatformsMenu');
if(settings){var subItems=settings.querySelectorAll('ul li a');subItems.forEach(function(link){if(link.textContent.trim().toLowerCase().includes('trading account')){link.closest('li').remove();}});}
var selectAccount=document.querySelector('#selectAccount');if(selectAccount)selectAccount.remove();var newNav=document.createElement('div');
var topGroup=document.createElement('ul');topGroup.className='x-navigation';topGroup.style.cssText='list-style:none;padding:0;margin:0;';topGroup.insertAdjacentHTML('beforeend','<li><a href="/"><span class="xn-text">My Account</span></a></li>');topGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/deposit"><span class="xn-text">Fund Account</span></a></li>');topGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/transactions"><span class="xn-text">Transactions</span></a></li>');if(trades){var tradeText=trades.querySelector('.xn-text');if(tradeText)tradeText.textContent='Trades';topGroup.appendChild(trades);}
newNav.appendChild(topGroup);newNav.insertAdjacentHTML('beforeend','<div class="bcm-divider"></div>');
newNav.insertAdjacentHTML('beforeend','<div class="bcm-group-label"><span class="fa fa-files-o"></span>ACCOUNT SETTINGS<span class="fa fa-chevron-down bcm-chevron"></span></div>');var settingsGroup=document.createElement('ul');settingsGroup.className='x-navigation';settingsGroup.style.cssText='list-style:none;padding:0;margin:0;';settingsGroup.insertAdjacentHTML('beforeend','<li><a href="/accounts"><span class="xn-text">Trading Accounts</span></a></li>');if(settings){var settingsSubItems=settings.querySelectorAll(':scope > ul > li');settingsSubItems.forEach(function(li){settingsGroup.appendChild(li);});}
newNav.appendChild(settingsGroup);newNav.insertAdjacentHTML('beforeend','<div class="bcm-divider"></div>');
newNav.insertAdjacentHTML('beforeend','<div class="bcm-group-label"><span class="fa fa-exchange"></span>REQUESTS<span class="fa fa-chevron-down bcm-chevron"></span></div>');var requestsGroup=document.createElement('ul');requestsGroup.className='x-navigation';requestsGroup.style.cssText='list-style:none;padding:0;margin:0;';requestsGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/request-status"><span class="xn-text">Request Status</span></a></li>');requestsGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/withdraw"><span class="xn-text">Withdrawal</span></a></li>');requestsGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/internal-transfers"><span class="xn-text">Internal Transfer</span></a></li>');requestsGroup.insertAdjacentHTML('beforeend','<li><a href="https://trade.blackcrownmarkets.com/change-leverage"><span class="xn-text">Change Leverage</span></a></li>');
newNav.appendChild(requestsGroup);newNav.insertAdjacentHTML('beforeend','<div class="bcm-divider"></div>');
newNav.insertAdjacentHTML('beforeend','<div class="bcm-group-label"><span class="fa fa-download"></span>TRADING PLATFORMS<span class="fa fa-chevron-down bcm-chevron"></span></div>');var platformsGroup=document.createElement('ul');platformsGroup.className='x-navigation';platformsGroup.style.cssText='list-style:none;padding:0;margin:0;';if(platforms){var platformSubItems=platforms.querySelectorAll(':scope > ul > li');platformSubItems.forEach(function(li){platformsGroup.appendChild(li);});}
platformsGroup.insertAdjacentHTML('beforeend','<li><a href="https://webtrader.blackcrownmarkets.com"><span class="xn-text">WebTrader</span></a></li>');newNav.appendChild(platformsGroup);
nav.parentNode.replaceChild(newNav,nav);var welcomeLi=document.querySelector('.desktop-welcome-li');var nameStrong=welcomeLi?welcomeLi.querySelector('.profile-data-name strong'):null;var nameText=nameStrong?nameStrong.textContent.trim():'';var nameMaxChars=18;if(nameText.length>nameMaxChars){nameText=nameText.slice(0,nameMaxChars).trim()+'…';}
if(welcomeLi)welcomeLi.remove();var profileFooter=document.createElement('div');profileFooter.className='bcm-sidebar-footer';profileFooter.innerHTML='<div class="bcm-sidebar-profile"><span class="bcm-sidebar-profile-icon"></span><span class="bcm-sidebar-profile-name">'+nameText+'</span><span class="bcm-sidebar-profile-chevron"></span></div><div class="bcm-divider"></div>';var logoutLink=document.querySelector('.desktop-logout-li a.mb-control[data-box="#mb-signout"]');if(logoutLink){var logoutLi=logoutLink.closest('.desktop-logout-li');logoutLink.classList.add('bcm-sidebar-logout');profileFooter.appendChild(logoutLink);if(logoutLi)logoutLi.style.display='none';}
sidebar.appendChild(profileFooter);
buildDashboardHeader();}
function buildDashboardHeader(){var mainContent=document.querySelector('.page-content-wrap');if(!mainContent)return;var selectEl=document.querySelector('#selectAccounts');var refreshEl=document.querySelector('.refreshWidgets')||document.querySelector('#refreshButton .fa-refresh');var refreshBtn=document.querySelector('#refreshButton');var header=document.createElement('div');header.className='bcm-dash-header';var selectorRow=document.createElement('div');selectorRow.className='bcm-selector-row';if(selectEl){var clonedSelect=selectEl.cloneNode(true);clonedSelect.removeAttribute('id');var selectWrap=document.createElement('div');selectWrap.className='bcm-select-wrap';selectWrap.appendChild(clonedSelect);selectorRow.appendChild(selectWrap);selectEl.closest('form')?selectEl.closest('form').style.display='none':selectEl.parentNode.style.display='none';}
if(refreshBtn){var refreshClone=refreshBtn.cloneNode(true);selectorRow.appendChild(refreshClone);refreshBtn.style.display='none';}
header.appendChild(selectorRow);mainContent.insertBefore(header,mainContent.firstChild);}
var BCM_RAW_PAYMENT_SELECTOR=false;
function buildDepositPage(){if(BCM_RAW_PAYMENT_SELECTOR)return;var panel=document.querySelector('#instances .panel');if(!panel||panel.dataset.bcmPayments)return;var body=panel.querySelector('.panel-body');var table=body?body.querySelector('table'):null;var rows=table?table.querySelectorAll('tbody tr'):[];if(!rows.length)return;panel.dataset.bcmPayments='1';
var methods=[];rows.forEach(function(row){var radio=row.querySelector('input[type=radio]');if(!radio)return;var infoDiv=row.querySelector('label > div');var nameEl=infoDiv?infoDiv.querySelector('b'):null;methods.push({radio:radio,name:nameEl?nameEl.textContent.trim():''});});
methods.forEach(function(m){m.radio.checked=false;});var fieldsPanel=document.querySelector('#client-fields');var instancesEl=document.querySelector('#instances');
var icons={other:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="4" width="22" height="16" rx="2"></rect><line x1="1" y1="10" x2="23" y2="10"></line></svg>'};
var groups=[{label:'EFT, Card & Other',match:/eft/i,icon:icons.other,color:'#7B2FBE',proc:'Instant',fee:'0%',limits:'—'},{label:'Bitcoin (BTC)',match:/letknow/i,img:'https://pp.ekspp.com/cdn/pm-icons/bitcoin/48/True.svg',color:'#fff',proc:'Instant',fee:'0%',limits:'20 – 9,000,000 USD/EUR'},{label:'USDT (ERC20)',match:/erc20/i,img:'https://pp.ekspp.com/cdn/pm-icons/usdt-erc20/48/True.svg',color:'#fff',proc:'Instant',fee:'0%',limits:'20 – 9,000,000 USD/EUR'},{label:'USDT (TRC20)',match:/trc20/i,img:'https://pp.ekspp.com/cdn/pm-icons/usdt-trc20/48/True.svg',color:'#fff',proc:'Instant',fee:'0%',limits:'20 – 9,000,000 USD/EUR'},{label:'Ethereum (ETH)',match:/ethereum/i,img:'https://pp.ekspp.com/cdn/pm-icons/ethereum/48/True.svg',color:'#fff',proc:'Instant',fee:'0%',limits:'20 – 9,000,000 USD/EUR'},{label:'USD Coin (USDC)',match:/usd coin/i,img:'https://pp.ekspp.com/cdn/pm-icons/usdc-erc20/48/True.svg',color:'#fff',proc:'Instant',fee:'0%',limits:'20 – 9,000,000 USD/EUR'}];
var list=document.createElement('div');list.className='bcm-payment-list';var cards=[];
groups.forEach(function(group){var method=methods.filter(function(m){return group.match.test(m.name);})[0];if(!method)return;
var option=document.createElement('div');option.className='bcm-payment-option';
var iconContent=group.img?'<img src="'+group.img+'" alt="'+group.label+'" loading="lazy">':(group.icon||group.symbol);
option.innerHTML='<div class="bcm-payment-head"><span class="bcm-payment-icon" style="background:'+group.color+'">'+iconContent+'</span><span class="bcm-payment-name">'+group.label+'</span></div><div class="bcm-payment-meta"><div class="bcm-payment-meta-row"><span class="bcm-payment-meta-label">Processing time</span><span class="bcm-payment-meta-value bcm-payment-pill">'+group.proc+'</span></div><div class="bcm-payment-meta-row"><span class="bcm-payment-meta-label">Fee</span><span class="bcm-payment-meta-value">'+group.fee+'</span></div><div class="bcm-payment-meta-row"><span class="bcm-payment-meta-label">Limits</span><span class="bcm-payment-meta-value">'+group.limits+'</span></div></div><span class="bcm-payment-radio"></span>';
option.addEventListener('click',function(){if(!method.radio.checked)method.radio.click();});
method.radio.addEventListener('change',function(){if(method.radio.checked){cards.forEach(function(c){c.el.classList.toggle('active',c.radio===method.radio);});if(fieldsPanel)fieldsPanel.classList.add('bcm-fields-visible');if(instancesEl)instancesEl.classList.add('bcm-instances-hidden');}});
cards.push({el:option,radio:method.radio});list.appendChild(option);});
table.style.display='none';body.appendChild(list);
if(fieldsPanel&&!fieldsPanel.querySelector('.bcm-payment-back')){var backBtn=document.createElement('button');backBtn.type='button';backBtn.className='bcm-payment-back';backBtn.textContent='Select Another Payment Method';backBtn.addEventListener('click',function(){methods.forEach(function(m){m.radio.checked=false;});cards.forEach(function(c){c.el.classList.remove('active');});fieldsPanel.classList.remove('bcm-fields-visible');if(instancesEl)instancesEl.classList.remove('bcm-instances-hidden');});var headingEl=fieldsPanel.querySelector('.panel-heading');if(headingEl){headingEl.appendChild(backBtn);}else{fieldsPanel.insertBefore(backBtn,fieldsPanel.firstChild);}}}
function showDepositConfirmModal(){if(document.querySelector('.bcm-modal-overlay'))return;var overlay=document.createElement('div');overlay.className='bcm-modal-overlay';overlay.innerHTML='<div class="bcm-modal"><p class="bcm-modal-text">Please allow time for funds to leave your crypto wallet and reflect in your trading account.<br>If it takes longer, please <a href="mailto:support@blackcrownmarkets.com" class="bcm-modal-link">contact support</a>.</p><a href="https://trade.blackcrownmarkets.com/" class="bcm-modal-btn">Back to Dashboard</a></div>';document.body.appendChild(overlay);}
function buildDepositSummaryPage(){var container=document.querySelector('#depositpage');if(!container||container.dataset.bcmStyled)return;var html=container.innerHTML;if(!/deposit summary/i.test(html))return;
var qrImg=container.querySelector('img');var addressLink=container.querySelector('a[href^="bitcoin:"]')||container.querySelector('a[href^="ethereum:"]')||container.querySelector('a[href^="litecoin:"]')||container.querySelector('a[href^="tron:"]')||container.querySelector('a[href^="usdt:"]')||container.querySelector('a');
if(!qrImg||!addressLink)return;container.dataset.bcmStyled='1';
function pick(re){var m=html.match(re);return m?m[1].replace(/&nbsp;/g,' ').trim():'';}
var amount=pick(/Amount:\s*([^<]+?)<br/i);
var rate=pick(/Provisional Exchange Rate:\s*([^<]+?)<br/i);
var coinAmount=pick(/\bBTC:\s*([^<]+?)<br/i);
var fee=pick(/Deposit Network Fee:\s*([^<]+?)<br/i);
var sendAmount=pick(/Please send BTC:\s*([^<]+?)\s*to:/i);
var address=addressLink.textContent.trim();var addressHref=addressLink.getAttribute('href');
var notesEl=container.querySelector('p[style*="font-size"]');
var notes=[];
if(notesEl){var rawNoteLines=notesEl.innerHTML.split(/<br\s*\/?>/i).map(function(s){return s.replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').trim();}).filter(Boolean);rawNoteLines.forEach(function(line){if(/^\d+\.\s*/.test(line)){notes.push(line.replace(/^\d+\.\s*/,''));}else if(notes.length){notes[notes.length-1]+=' '+line;}else{notes.push(line);}});}
if(notes.length){notes[0]='Please double-check that the address and network match exactly before sending — deposits sent to the wrong address or network cannot be recovered.';}
var ICONS={user:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',shield:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-7.35 8.95a1 1 0 0 1-1.3 0C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/></svg>',shieldCheck:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-7.35 8.95a1 1 0 0 1-1.3 0C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m9 12 2 2 4-4"/></svg>',coin:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M14.8 9A2 2 0 0 0 13 8h-2a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4h-2a2 2 0 0 1-1.8-1"/><path d="M12 6v2m0 8v2"/></svg>',copy:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>'};
var rows=[{label:'Amount',value:amount,icon:ICONS.user},{label:'Provisional Exchange Rate',value:rate,icon:ICONS.shield},{label:'BTC',value:coinAmount,icon:ICONS.coin},{label:'Deposit Network Fee',value:fee,icon:ICONS.shieldCheck}];
var rowsHtml=rows.filter(function(r){return r.value;}).map(function(r){return '<div class="bcm-ds-row"><span class="bcm-ds-row-icon">'+r.icon+'</span><span class="bcm-ds-row-label">'+r.label+':</span><span class="bcm-ds-row-value">'+r.value+'</span></div>';}).join('');
var notesListHtml=notes.map(function(t){return '<li>'+t+'</li>';}).join('');
container.innerHTML='<div class="bcm-deposit-summary"><div class="bcm-ds-card"><div class="bcm-ds-main"><h2 class="bcm-ds-title">Deposit Summary</h2><span class="bcm-ds-title-bar"></span><div class="bcm-ds-rows">'+rowsHtml+'</div>'+(sendAmount?'<p class="bcm-ds-send">Please send BTC '+sendAmount+' to:</p>':'')+'<div class="bcm-ds-address-row"><span class="bcm-ds-address-label">Address:</span><a href="'+addressHref+'" target="_blank" rel="noopener" class="bcm-ds-address">'+address+'</a><button type="button" class="bcm-ds-copy" data-address="'+address+'" title="Copy address">'+ICONS.copy+'</button></div><p class="bcm-ds-scan">Or simply scan it using QR &ndash; barcode scanner:</p></div><div class="bcm-ds-qr-wrap"></div></div>'+(notes.length?'<div class="bcm-ds-notes"><span class="bcm-ds-notes-icon">'+ICONS.shield+'</span><ol class="bcm-ds-notes-list">'+notesListHtml+'</ol></div>':'')+'</div>';
var qrWrap=container.querySelector('.bcm-ds-qr-wrap');qrImg.classList.add('bcm-ds-qr');qrWrap.appendChild(qrImg);
var confirmBtn=document.createElement('button');confirmBtn.type='button';confirmBtn.className='bcm-ds-confirm-btn';confirmBtn.textContent='I have completed my Deposit';confirmBtn.addEventListener('click',function(){showDepositConfirmModal();});qrWrap.appendChild(confirmBtn);
var copyBtn=container.querySelector('.bcm-ds-copy');if(copyBtn){copyBtn.addEventListener('click',function(){var value=copyBtn.getAttribute('data-address');if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(value);}else{var ta=document.createElement('textarea');ta.value=value;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');}catch(e){}document.body.removeChild(ta);}copyBtn.classList.add('bcm-ds-copied');setTimeout(function(){copyBtn.classList.remove('bcm-ds-copied');},1500);});}}
function relocateDisclaimers(){var mainContent=document.querySelector('.page-content-wrap');if(!mainContent)return;var disclaimer=document.querySelector('.disclaimer-color');var footer=document.querySelector('.footer-color');if(disclaimer)mainContent.appendChild(disclaimer);if(footer)mainContent.appendChild(footer);}
function buildLoginPage(){var body=document.querySelector('.login-body');if(!body||body.dataset.bcmLogin)return;body.dataset.bcmLogin='1';document.documentElement.classList.add('bcm-login-page');var left=document.createElement('div');left.className='bcm-login-left';while(body.firstChild){left.appendChild(body.firstChild);}var titleEl=left.querySelector('.login-title');if(titleEl){var subtitle=document.createElement('div');subtitle.className='bcm-login-subtitle';subtitle.textContent='Access your Black Crown Markets account to manage your trading with ease.';titleEl.insertAdjacentElement('afterend',subtitle);}var right=document.createElement('div');right.className='bcm-login-right';right.innerHTML='<img class="bcm-login-logo" src="https://ffxlryusmstnfjedleds.supabase.co/storage/v1/object/public/Assets/blackcrown%20white.svg" alt="Black Crown Markets"/>';body.appendChild(left);body.appendChild(right);body.classList.add('bcm-login-card');document.body.appendChild(body);}
function buildRegistrationPage(){var body=document.querySelector('.registration-body');if(!body||body.dataset.bcmLogin)return;body.dataset.bcmLogin='1';document.documentElement.classList.add('bcm-login-page');var left=document.createElement('div');left.className='bcm-login-left';while(body.firstChild){left.appendChild(body.firstChild);}var stepNumbers=left.querySelectorAll('.steps_2 .stepNumber');stepNumbers.forEach(function(el,i){el.textContent=String(i+1);});var right=document.createElement('div');right.className='bcm-login-right';right.innerHTML='<img class="bcm-login-logo" src="https://ffxlryusmstnfjedleds.supabase.co/storage/v1/object/public/Assets/blackcrown%20white.svg" alt="Black Crown Markets"/>';body.appendChild(left);body.appendChild(right);body.classList.add('bcm-login-card');document.body.appendChild(body);}
function adjustSidebarHeight(){var sidebar=document.querySelector('.page-sidebar');var header=document.querySelector('.main-header')||document.querySelector('.x-navigation-horizontal');if(!sidebar||!header)return;var headerHeight=header.getBoundingClientRect().height;sidebar.style.setProperty('min-height','calc(100vh - '+headerHeight+'px)','important');}
function markActiveNavItem(){var links=document.querySelectorAll('.page-sidebar .x-navigation a[href]');var currentPath=window.location.pathname.replace(/\/$/,'')||'/';links.forEach(function(a){var linkPath;try{linkPath=new URL(a.getAttribute('href'),window.location.href).pathname.replace(/\/$/,'')||'/';}catch(e){return;}if(linkPath===currentPath){var li=a.closest('li');if(li)li.classList.add('active');}});}
function initGroupToggles(){var labels=document.querySelectorAll('.page-sidebar .bcm-group-label');labels.forEach(function(label){label.classList.add('bcm-collapsed');var list=label.nextElementSibling;if(list)list.style.display='none';label.addEventListener('click',function(){label.classList.toggle('bcm-collapsed');var list=label.nextElementSibling;if(list)list.style.display=label.classList.contains('bcm-collapsed')?'none':'';});});}
function observeContentChanges(){var target=document.querySelector('.page-content-wrap')||document.body;if(!target||typeof MutationObserver==='undefined')return;var observer=new MutationObserver(function(){buildDepositPage();buildDepositSummaryPage();});observer.observe(target,{childList:true,subtree:true});}
function init(){buildSidebar();buildDepositPage();buildDepositSummaryPage();relocateDisclaimers();buildLoginPage();buildRegistrationPage();adjustSidebarHeight();window.addEventListener('resize',adjustSidebarHeight);markActiveNavItem();initGroupToggles();observeContentChanges();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}})();
